/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package td.tdd;

public class Dictionary {
    public Dictionary() {
    }

    public String getName(){
        return "Example";
    }
}
