/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package td.tdd;

import org.junit.Test;
import static org.junit.Assert.*;

public class DictionaryTest {
    Dictionary dict = new Dictionary();
    
    @Test public void testDictionaryName() {
        assertThat(dict.getName(), equalTo("Example"));
        }
}